### ISSUE TITLE
Log window text is unreadable in Dark Mode

### ISSUE THREAD

**Issue by inexorabletash** [ksherlock/ample#11]
* macOS Catalina - Dark Mode
* Ample Release 8

Repro:
1. Set Mac to Dark Mode: Apple > System Preferences... > General > Appearance: Dark
1. Launch Ample
2. Pick a machine, e.g. Apple IIe
3. Select Window Mode other than Full Screen
4. Launch

Result:
Ample Log window has black text on dark gray background.

![image](https://user-images.githubusercontent.com/771547/103450173-4a7d4c00-4c67-11eb-89b6-1c2160bf5a5e.png)

**Comment by ksherlock** [comment]
Thanks!  Fixed with c88fe39
