### ISSUE TITLE
Crash when trying to start debug mode

### ISSUE THREAD

**Issue by frankmilliron** [ksherlock/ample#22]
2022-11-25 07:25:07.003 mame64[849:22068] *** Assertion failure in -[NSPopUpButton initWithFrame:], NSView.m:1353
Caught unhandled exception

[Caught signal 11 (Segmentation fault: 11)]

MacOS 11.7.1 Big Sur

**Comment by frankmilliron** [comment]
MAME path: /Applications/Emulators/Ample.app/Contents/MacOS/mame64
Working Directory: /Users/Frank/Library/Application Support/Ample
Debug Build: Disabling input grab for -debug
Debug Build: Disabling input grab for -debug
Debug Build: Disabling input grab for -debug
vmnet_helper: vmnet_start_interface failed


	vmnet_helper must be run as root.
	Go to Ample -> Preferences and Fix VMNet Permissions.

2022-11-25 07:38:39.948 mame64[674:9188] *** Assertion failure in -[NSPopUpButton initWithFrame:], NSView.m:1353
Caught unhandled exception



[Caught signal 11 (Segmentation fault: 11)]

**Comment by frankmilliron** [comment]
Works fine in 'non-debug mode'. Was fine in debug mode then stopped working completely and now won't start debug at all.

**Comment by frankmilliron** [comment]
A restart of the machine did not help clear the issue.

**Comment by ksherlock** [comment]
Could you include the full command with arguments and confirm which version of Ample you're using (Version 0.249-u2 (37) is the most recent).

Thanks

**Comment by frankmilliron** [comment]
Hey Kelvin. Thanks for Ample. It's a great tool. I use it frequently for Total Replay, so It's generally up to date. It's "Version 0.249-u2 (37)". My config hasn't recently changed. Just weird it started recently out of nowhere. maybe something changed in mame.ini?

`mame64 apple2gs -skip_gameinfo -nosamples -debug -window -nomax -ramsize 4M -sl1 ssc -sl2 uthernet2 -sl7 cffa2 -gameio joy -hard1 /Users/Frank/Desktop/4cade.hdv`

**Comment by frankmilliron** [comment]
```
cd /Applications/Emulators/Ample.app/Contents/MacOS
./mame64 apple2gs -skip_gameinfo -nosamples -window -nomax -ramsize 4M -sl1 ssc -sl7 cffa2 -gameio joy -nomouse -hard1 /Users/Frank/Desktop/4cade.hdv
```

yields...

`Unable to find the BGFX path bgfx, please install it or fix the bgfx_path setting to use the BGFX renderer.
341s0632-2.bin NOT FOUND (tried in apple2gs)
apple2gs.chr NOT FOUND (tried in apple2gs)
341-0728 NOT FOUND (tried in apple2gs)
341-0748 NOT FOUND (tried in apple2gs)
341-0132-d.e12 NOT FOUND (tried in apple2gs)
341-0065-a.bin NOT FOUND (tried in a2ssc apple2gs)
cffa20eec02.bin NOT FOUND (tried in a2cffa2 apple2gs)
Fatal error: Required files are missing, the machine cannot be run.`

**Comment by ksherlock** [comment]
I can't reproduce the NSPopUpButton problem on my computers (10.14.6 and 12.6.1). Is there a crash log in Console.app?(possibly under User Reports or Crash Reports)

To run on the command-line, you need to be in the ~/Library/ApplicationSupport/Ample directory to find the ROMs and other config files. File -> Export Shell Script handles that.

**Comment by frankmilliron** [comment]
I trashed the Application Support directory and reinstalled the app and it's gone away.
Thanks for the tip about the Shell Script. I didn't know that was in there.

**Comment by frankmilliron** [comment]
This happened again. I think I've tracked it down to the "apple2gs.cfg" file in "cfg" directory in Application Support. The attached file will always throw the error with 'debug' turned on. It will launch a non-debug session fine.
[apple2gs.cfg.zip](https://github.com/ksherlock/ample/files/10097688/apple2gs.cfg.zip)

**Comment by ksherlock** [comment]
I found this comment: https://github.com/mamedev/mame/commit/c76cf754b3cb1a07f8d3ca585bb3a055d78f25be#diff-9be1ff78854574c4586f244cbc2c9cb731f270a10c608cd27ae7ca51a0dfc660

> I actually need running without -debug to wipe the config. There's been a bug in the Cocoa debugger since it got window saving where sometimes the state is corrupted and MAME crashes until you run without -debug to wipe it.

So it looks like a known issue and somewhat random (I've never encountered it). Your config file, at least on 10.14, hasn't given me any problems.

**Comment by frankmilliron** [comment]
I updated my laptop to "Monterey" 12.6.1 recently and it seems to have stopped. Maybe just some bugs in Big Sur! Thanks for looking into it.
