### ISSUE TITLE
add mame keyboard cheat sheet

### ISSUE THREAD

**Issue by ksherlock** [ksherlock/ample#8]

**Comment by inexorabletash** [comment]
Please include shortcuts for MacBook (etc) keyboards that require modifiers for shortcuts (<kbd>fn</kbd>+<kbd>delete</kbd> to toggle modes, etc).

**Comment by ksherlock** [comment]
These are the keys: 

https://github.com/ksherlock/ample/wiki/Keyboard-Cheat-Sheet

option-enter (for full screen toggle) and page down (fn down arrow?) might require the fn key. Can you confirm?

**Comment by inexorabletash** [comment]
Testing in Ample 9.1, MacBook Air

* <kbd>option</kbd>+<kbd>return</kbd> (a.k.a. enter) toggles fullscreen. <kbd>fn</kbd> is *not* required. Also *does not* require being in partial emulation mode.
* <kbd>fn</kbd>+<kbd>down</kbd> fast forwards. It *does* require being in partial emulation mode.
* <kbd>F10</kbd> to toggle throttle *does* seem to work for me (as noted, it's literally <kbd>fn</kbd>+<kbd>F10</kbd>), despite the wiki page. It *does* require being in partial emulation mode.

A working key to release the mouse pointer would be very welcome.

**Comment by ksherlock** [comment]
Thanks. Currently, the most consistent way to release the mouse pointer is to pause the machine (command-option-p being the fastest way to do that)

**Comment by ksherlock** [comment]
The cheatsheet is now included in Ample 10.

**Comment by inexorabletash** [comment]
Release 10: **Help > MAME Keyboard Cheat Sheet** doesn't appear to do anything on my system. In contrast, **Help > MAME Apple II Wiki** and **Help > MAME Documentation** both correctly open new tabs in my default browser.

Did a glitch sneak in at the last moment?

**Comment by ksherlock** [comment]
That's interesting.  It doesn't work for me in the released version either but it does when I build and launch from Xcode.  There is an error in the console log that "an uncaught exception was raised". Further details are left to the imagination.  Since the cheat sheet uses web view and I enable the webkit developer tools, I wonder if that causes a problem when code signing is in effect, which in turn prevents the window from displaying.

**Comment by ksherlock** [comment]
Fixed in https://github.com/ksherlock/ample/releases/tag/release-11

I didn't include the webkit framework (which wasn't needed when testing).
